/** Logo CH Service para ticket térmico de 58 mm. Raster 1 bit, 1 = negro. */
export const CHSERVICE_LOGO_WIDTH = 256;
export const CHSERVICE_LOGO_HEIGHT = 275;

const LOGO_BASE64 =
  'AAAAAAAAAAAAAAAA///////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf///////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'P////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAB/////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////////////4' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAD//////////////4AAAAAAAAAAAAAAAAAAAAAAAAAAA///////////////wAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAH///////////////gAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAH//' +
  'wAAAAAAAAAA//+AAAAAAAAAAAAAAAAAAAAAAAAAA//4AAAAAAAAAAAP/8AAAAAAAAAAAAAAAAAAAAAAAAAH/+AAAAAAAAAAAAP/4' +
  'AAAAAAAAAAAAAAAAAAAAAAAAA//gAAAAAAAAAAAAf/wAAAAAAAAAAAAAAAAAAAAAAAAH/8AAAAAAAAAAAAAf/gAAAAAAAAAAAAAA' +
  'AAAAAAA/gA//gAAAAAAAAAAAAA//AB/gAAAAAAAAAAAAAAAAB//gH/8AAAAAAAAAAAAAB/+AP/4AAAAAAAAAAAAAAAAf/+A//gAA' +
  'AAAAAAAAAAAD/8B//4AAAAAAAAAAAAAAAD//8H/8AAAAAAAAAAAAAAH/4P//wAAAAAAAAAAAAAAAf//w//gAAAAAAAAAAAAAAP/w' +
  '///gAAAAAAAAAAAAAAB///H/8AAAAAAAAAAAAAAAf/j//+AAAAAAAAAAAAAAAH//+//gAAAAAAAAAAAAAAA//P//4AAAAAAAAAAA' +
  'AAAAf////8AAAAAAAAAAAAAAAB/////gAAAAAAAAAAAAAAB/////gAAAAAAAAAAAAAAAD////+AAAAAAAAAAAAAAAH////4AAAAA' +
  'AAAAAAAAAAAH////4AAAAAAAAAAAAAAAP////AAAAAAAAAAAAAAAAAP////AAAAAAAAAAAAAAAAf///4AAAAAAAAAAAAAAAAAf//' +
  '/8AAAAAAAAAAAAAAAB////AAAAAAAAAAAAAAAAAA////gAAAAAAAAAAAAAAAB///4AAAAAAAAAAAAAAAAAB///8AAAAAAAAAAAAA' +
  'AAAD///AAAAAAAAAAAAAAAAAAD///AAAAAAAAAAAAAAAAAB//4AAAAAAAAAAAAAAAAAAH//wAAAAAAAAAAAAAAAAAB//AAAAAAAA' +
  'AAAAAAAAAAAP/4AAAAAAAAAAAAAAAAAAH/4AAAAAAAAAAAAAAAAAAAf/wAAAAAAAAAAAAAAAAAA//AAAAAAAAAAAAAAAAAAAA//g' +
  'AAAAAAAAAAAAAAAAAH////////////////////////AAAAAAAAAAAAAAAAAA////////////////////////+AAAAAAAAAAAAAAA' +
  'AAH////////////////////////4AAAAAAAAAAAAAAAAA/////////////////////////wAAAAAAAAAAAAAAAAH////////////' +
  '/////////////gAAAAAAAAAAAAAAAA//////////////////////////AAAAAAAAAAAAAAAAH/////////////////////////+A' +
  'AAAAAAAAAAAAAAA//////////////////////////8AAAAAAAAAAAAAAAH//////////////////////////4AAAAAAAAAAAAAAA' +
  'f//////////////////////////wAAAAAAAAAAAAAAD///////////////////////////AAAAAAAAAAAAAAAf//////////////' +
  '////////////+AAAAAAAAAAAAAAB///////////////////////////8AAAAAAAAAAAAAAP///////////////////////////wA' +
  'AAAAAAAAAAAAB////////////////////////////gAAAAAAAAAAAAAH/gH//////////////////////AP+AAAAAAAAAAAAAA/4' +
  'AH/////////////////////wAf8AAAAAAAAAAAAAD/AAH////////////////////4AA/wAAAAAAAAAAAAAP4AAH////////////' +
  '////////AAB/gAAAAAAAAAAAAB/AAAH///////////////////wAAD+AAAAAAAAAAAAAH8AAAP//////////////////8AAAP4AA' +
  'AAAAAAAAAAAfgAAAP//////////////////gAAAfwAAAAAAAAAAAAD+AAAAf/////////////////4AAAB/AAAAAAAAAAAAAP4AA' +
  'AA//////////////////AAAAH8AAAAAAAAAAAAA/gAAAB/////////////////4AAAAfwAAAAAAAAAAAAD+AAAAB////////////' +
  '/////AAAAB/AAAAAAAAAAAAAP4AAAAD////////////////4AAAAH8AAAAAAAAAAAAA/gAAAAP/gAAAAAAAAAAAAf/AAAAAfwAAA' +
  'AAAAAAAAAD/AAAAAf8AAAAAAAAAAAAA/4AAAAD/AAAAAAAAAAAAAP8AAAAA/gAAAAAAAAAAAAB/gAAAAP8AAAAAAAAAAAAA/4AAA' +
  'AD+AAAAAAAAAAAAAH8AAAAA/wAAAAAAAAAAAAD/gAAAAP4AAAAAAAAAAAAAf4AAAAH/AAAAAAAAAAAAAP/AAAAB/wAAAAAAAAAAA' +
  'AB/gAAAA/8AAAAAAAAAAAAA//AAAAP/AAAAAAAAAAAAAP/AAAAH/wAAAAAAAAAAAAD//AAAP/8AAAAAAAAAAAAA//wAAB//AAAAA' +
  'AAAAAAAAP///////4AAAAAAAAAAAAD///////8AAAAAAAAAAAAA////////gAAAAAAAAAAAAf///////wAAAAAAAAAAAAD//////' +
  '//AAAAAAAAAAAAB////////AAAAAAAAAAAAAP///////8AAAAAAAAAAAAP///////8AAAAAAAAAAAAA////////4AAAAAAAAAAAA' +
  '////////wAAAAAAAAAAAAD////////gAAAAAAAAAAAH////////AAAAAAAAAAAAAP////////AAAAAAAAAAAA////////8AAAAAA' +
  'AAAAAAA////////+AAAAAAAAAAAH////////wAAAAAAAAAAAAD////////+AAAAAAAAAAB/////////AAAAAAAAAAAAAP///////' +
  '/////////////////////8AAAAAAAAAAAAA/////////////////////////////wAAAAAAAAAAAAD//////////////////////' +
  '///////AAAAAAAAAAAAAP/4AAD//////////////////wAAH/8AAAAAAAAAAAAA//AAAD/////////////////+AAAP/wAAAAAAA' +
  'AAAAAD/4AAAP/////////////////wAAAf/AAAAAAAAAAAAAP/gAAAf////////////////+AAAB/8AAAAAAAAAAAAA/+AAAA//4' +
  'AAAAAAAAAAAB//wAAAH/wAAAAAAAAAAAAD/4AAAB//AAAAAAAAAAAAD/+AAAAf/AAAAAAAAAAAAAP/gAAAD/+AAAAAAAAAAAAP/4' +
  'AAAB/8AAAAAAAAAAAAA//AAAAH/4AAAAAAAAAAAB//AAAAH/wAAAAAAAAAAAAD/8AAAAf/gAAAAAAAAAAAH/4AAAA//AAAAAAAAA' +
  'AAAAP/4AAAA//AAAAAAAAAAAA//AAAAD/8AAAAAAAAAAAAAf/wAAAB/+AAAAAAAAAAAH/4AAAAf/wAAAAAAAAAAAAB//gAAAD/8A' +
  'AAAAAAAAAAf/AAAAD/+AAAAAAAAAAAAAH//AAAAH/4AAAAAAAAAAD/4AAAA//4AAAAAAAAAAAAAP//AAAAP/wAAAAAAAAAA//gAA' +
  'AH//AAAAAAAAAAAAAAf//gAAA//8AAAAAAAAA//+AAAH//8AAAAAAAAAAAAAB////////////////////////////gAAAAAAAAAA' +
  'AAAD///////////////////////////8AAAAAAAAAAAAAAH///////////////////////////gAAAAAAAAAAAAAAP//////////' +
  '////////////////+AAAAAAAAAAAAAAA///////////////////////////4AAAAAAAAAAAAAAD/////////////////////////' +
  '//gAAAAAAAAAAAAAAP//////////////////////////8AAAAAAAAAAAAAAA///////////////////////////wAAAAAAAAAAAA' +
  'AAD///////////////////////////gAAAAAAAAAAAAAAP////wAAAAAAAAAAAAAAAAD////+AAAAAAAAAAAAAAA/////AAAAAAA' +
  'AAAAAAAAAAH////wAAAAAAAAAAAAAAD////8AAAAAAAAAAAAAAAAA/////AAAAAAAAAAAAAAAP////wAAAAAAAAAAAAAAAAD////' +
  '8AAAAAAAAAAAAAAA/////AAAAAAAAAAAAAAAAAP////wAAAAAAAAAAAAAAD////8AAAAAAAAAAAAAAAAAf////AAAAAAAAAAAAAA' +
  'AP////gAAAAEAAAAAAAAAAAB////8AAAAAAAAAAAAAAAf///+AAAAAIAAAAAAAAAAAH////gAAAAAAAAAAAAAAB////wAAAAAwAA' +
  'AAAAAAAAAP///+AAAAAAAAAAAAAAAD///+AAAAABgAAAAAAAAAAAf///wAAAAAAAAAAAAAAAD///wAAAAAGAAAAAAAAAAAA///+A' +
  'AAAAAAAAAAAAAAAD//8AAAAAAcAAAAAAAAAAAA///gAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4AAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAPwAAAAAAAAAAAB/wAAAAAAAAAAAAAAAAB/4AAAAAAAA/gAAAAAAAAAAA//4AAAAAAAAAAAAAAAAf' +
  '/4AAAAAAAB+AAAAAAAAAAAP//4AAAAAAAAAAAAAAAH//4AAAAAAAH8AAIAAAAAAAB///4AAAAAAAAAAAAAAB///4AAAAAAAf4AAg' +
  'AAAAAAAP///wAAAAAAAAAAAAAAP///wAAAAAAA/wAHAAAAAAAD////gAAAAAAAAAAAAAB////gAAAAAAD/AA8AAAAAAAP////AAA' +
  'AAAAAAAAAAAP////AAAAAAAH+AH4AAAAAAB////+AAAAAAAAAAAAAB////+AAAAAAAf8AfgAAAAAAP////4AAAAAAAAAAAAAH///' +
  '/8AAAAAAB/4D/AAAAAAB//+AAAAAAAAAAAAAAAAAAP//wAAAAAAD/wf8AAAAAAH//4AAAAAAAAAAAAAAAAAAf//gAAAAAAP/B/wA' +
  'AAAAA///AAAAAAAAAAAAAAAAAAA///AAAAAAA/+P/gAAAAAD//4AAAAAAAAAAAAAAAAAAB////////AB/9/+AA///////AAAAAAA' +
  'AAAAAAAAAAAAD///////8AH///8AD//////4AAAAAAAAAAAAAAAAAAAP///////wAP///wAP//////AAAAAAAAAAAAAAAAAAAAf/' +
  '//////AA////AA//////8AAAAAAAAAAAAAAAAAAAA///////8AD///+AD//////gAAAAAAAAAAAAAAAAAAAB///////wAH///4AP' +
  '/////+AAAAAAAAAAAAAAAAAAAAH///////AAf///wA//////4AAAAAAAAAAAAAAAAAAAAf//////8AA////AD//////wAAAAAAAA' +
  'AAAAAAAAAAAD///////wAD///8AP//////AAAAAAAAAAAAAAAAAAAAf///////AAP///4A//////+AAAAAAAAAAAAAAAAAAAB///' +
  '////8AAf///gD//////8AAAAAAAAAAAAAAAAAAAP///////wAB////AP//////4AAAAAAAAAAAAAAAAAAB//+AAAAAAAH/9/8AAA' +
  'AAf//wAAAAAAAAAAAAAAAAAAP//gAAAAAAAP/j/wAAAAAf//gAAAAAAAAAAAAAAAAAB//+AAAAAAAA/8H/gAAAAB///AAAAAAAAA' +
  'AAAAAAAAAP//wAAAAAAAB/wP+AAAAAD////+AAAAAAAAAAAAAB/////AAAAAAAAH+Af8AAAAAH////4AAAAAAAAAAAAAH////4AA' +
  'AAAAAAfwB/wAAAAAf////AAAAAAAAAAAAAAP////AAAAAAAAA+AD/AAAAAA////4AAAAAAAAAAAAAAf///4AAAAAAAAD4AH+AAAA' +
  'AB////AAAAAAAAAAAAAAA////AAAAAAAAAPAAP4AAAAAB///4AAAAAAAAAAAAAAB///4AAAAAAAAAYAAfwAAAAAD//+AAAAAAAAA' +
  'AAAAAAB//+AAAAAAAAABgAB/AAAAAAD//gAAAAAAAAAAAAAAAD//gAAAAAAAAAAAAD8AAAAAAB/wAAAAAAAAAAAAAAAAB/wAAAAA' +
  'AAAAAAAAH4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/AAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAHgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHwAAAAAAAD4AAAAAAAAAAAAAAA+AAAAAAAAAAAAAAAD/4B8AHgAB/8A//' +
  '8P/8D4AHz4Af/AP//gAAAAAAAAAA//wHwAeAAP/4D//w//8PgAeHgD/+A//+AAAAAAAAAAH//gfAB4AB//wP//D//4eAB4eA//8D' +
  '//4AAAAAAAAAA/h/B8AHgAPw/g//8P//x8APh4D+P4P//gAAAAAAAAAD4B+HwAeAA+A+DwAA+AfHwA8HgfgPw+AAAAAAAAAAAAfA' +
  'D4fAB4AHwB4PAAD4A8PADweD4AfD4AAAAAAAAAAAB8AHh8AHgAfAHg8AAPgD4+AfB4PgA+PgAAAAAAAAAAAPgAeHwAeAB8AADwAA' +
  '+APj4B4Hh8AD4+AAAAAAAAAAAA+AAAfAB4ADwAAPAAD4A+HgHgeHwAAD4AAAAAAAAAAADwAAB8AHgAPwAA8AAPgD4fA+B4fAAAPg' +
  'AAAAAAAAAAAPAAAHwAeAA/4ADwAA+AfB8D4Hh4AAA+AAAAAAAAAAAA8AAAf//4AB/8AP/+D4D8DwPAeHgAAD//wAAAAAAAAADwAA' +
  'B///gAD/8A//4P//gPB8B4eAAAP//AAAAAAAAAAfAAAH//+AAD/8D//g//+A+HwHh4AAA//8AAAAAAAAAA8AAAf//4AAB/4P/+D/' +
  '/gB4eAeHgAAD//gAAAAAAAAADwAAB8AHgAAA/g8AAP/8AHh4B4eAAAPgAAAAAAAAAAAPAAAHwAeAAAA/DwAA+HwAfPgHh8AAA+AA' +
  'AAAAAAAAAA+AAAfAB4AAAB8PAAD4PgA88AeHwAAD4AAAAAAAAAAAD4AHx8AHgAGAHw8AAPgeADzwB4fAA+PgAAAAAAAAAAAHwAfH' +
  'wAeAB4APDwAA+B8AP/AHg+AD4+AAAAAAAAAAAAfAD4fAB4AHwB8PAAD4D4Af4AeD4AfD4AAAAAAAAAAAA+Afh8AHgAfAHw8AAPgP' +
  'gB/gB4HwD8PgAAAAAAAAAAAD+D8HwAeAA/B+D4AA+AfAH+AHgfwfg+AAAAAAAAAAAAH//gfAB4AD//4P//j4B8APwAeA//8D//4A' +
  'AAAAAAAAAP/8B8AHgAH//A//+PgD4A/AB4B//wP//gAAAAAAAAAAf/gHwAeAAH/4D//4+APgD8APgB/8A//+AAAAAAAAAAAP4AOA' +
  'AIAAH8AP//BQAeAHgAUAB/AB//4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAADgAAAABwAAAADAAAAAAAAAADgAAAAwAAAAAAA/8wD/w/j/7/gfwcDjB/AOAAcHA7/4/g8B4P4/+/4Y///jAP+H/P/P/D/' +
  'h4OMP+B4ADwMDv/n/DwHj/z/7/xj/+AMA4A4ODA4ccHHw4xwcHwAPgwODA4OPg+OHg4OHGAO4AwDgDAYMDgxgOfDjHAwfAA+DA4O' +
  'DAc+D5wODg4OYBzgDAOAcBAwODOA5+OM4CDsAHYMDg4cBz4PnAYODg5gHOAMA4BwADA4M4DnY4zgAM4AZwwODhwHPx+YBw4ODGA4' +
  '/4wD/nAAMDjzgGdzjOAAzgBnDA4OHAM7G5gHDg48YHD/jAP+cAAwP+OAZzuM4AHGAOMMDg4cAzsbmAcOD/hgcOAMA4BwADA/w4Bn' +
  'G4zgAYcA44wODhwDO7uYBw4P8GDg4AwDgHAAMDnDgOcfjOAB/wD/jA4OHAc5s5gGDg4wYcDgDAOAcBgwOOOA5w+MYDP/Af+MDA4M' +
  'BznznAYODjhhwOAMA4A4ODA44cHHD4xwc4OBwc4cDg4OOfOODg4OGGOA/o/z/hxwMDhw48cHjDzzA4GBzzwOB5444488Dg4cZ/7/' +
  'z/v/H/AwOHD/hweMH+cBg4DH+A4D/Djjh/gODg5n//+P8f8HwDAwMD4CAwwPhgGDAMHgDAHwEEMB8AwEDmP/AAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  '4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH+H+A/gH4P8A4DgHA4A/BgfgcDAAAAAAAAAAAAAAAAAf8f8H/A/4' +
  '/8DwPA8DwH+GD/hwMAAAAAAAAAAAAAAAABg5w44eHDjhwPA8DwPA4cYcOHgwAAAAAAAAAAAAAAAAGDnBjA44HODh+DwPB8HA5jgc' +
  'eDAAAAAAAAAAAAAAAAAYGcGcBzAI4OG4Ph8G4cDGMAx8MAAAAAAAAAAAAAAAABgZgZgHMADg4Zg2GwZhgAYwDG4wAAAAAAAAAAAA' +
  'AAAAGDnDmAdwAOHDnDYbDmGABnAOZjAAAAAAAAAAAAAAAAAf8f8YB3D8/8OcNzsMcYAGcA5nMAAAAAAAAAAAAAAAAB/h/hgHcPz/' +
  'AwwzMwwxgAZwDmMwAAAAAAAAAAAAAAAAHAHOHAcwHOcH/jMzH/mABjAMY7AAAAAAAAAAAAAAAAAYAYYcBzgc44f+M/Mf+cDmOAxh' +
  '8AAAAAAAAAAAAAAAABgBhw4OOBzhhw4x4xw5wOY4HGDwAAAAAAAAAAAAAAAAGAGDDx4cPOHOBzHjOBjhxhw4YPAAAAAAAAAAAAAA' +
  'AAAYAcOH/A/84M4HMeM4HH+GD/BgcAAAAAAAAAAAAAAAABgBgYP4B+zg7AMwwzAMPwYH4GBwAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADADADAHAAAAABwAHAGAEAAAAAAAAAAAAAAAAAA' +
  'AAAAA/A/B/B/Af+f4fwB/B+AwAAAAAAAAAAAAAAAAAAAAAAH+H+H+P+B/5/j/gP8P8PAAAAAAAAAAAAAAAAAAAAAAA4c4c4Y4YAD' +
  'mAOOAw5w58AAAAAAAAAAAAAAAAAAAAAADhzBzBzBgAcYAwYHBnDmwAAAAAAAAAAAAAAAAAAAAAAMDMDMHAGABhgABgAOYGDAAAAA' +
  'AAAAAAAAAAAAAAAAAAwM4cwcA4AOP8AOAA5gYMAAAAAAAAAAAAAAAAAAAAAADA7hzhwHAA4/4BwAHGBgwAAAAAAAAAAAAAAAAAAA' +
  'AAAMDn/H/A8ADDhwOAA4YGDAAAAAAAAAAAAAAAAAAAAAAAwMP8f8HAAcAHBwAPBgYMAAAAAAAAAAAAAAAAAAAAAADAwAwBw4ABgA' +
  'ceAB4GBgwAAAAAAAAAAAAAAAAAAAAAAOHAHAHHAAOABxwAHAcODAAAAAAAAAAAAAAAAAAAAAAA4c4c4Y4AA4OHOAA4Bw4MAAAAAA' +
  'AAAAAAAAAAAAAAAABzhzj3j/gDA84/4H/jnAwAAAAAAAAAAAAAAAAAAAAAAH+H8H8P/AcB/n/gf+H8DAAAAAAAAAAAAAAAAAAAAA' +
  'AAHgHgPg/4BwB4P+B/4PAMAAAAAAAAAAAA==';

export function chserviceLogoRaster(): Uint8Array {
  const binary = atob(LOGO_BASE64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}
